services:
  postgres:
    image: postgres:18
    container_name: the_room_of_secrets
    environment:
      POSTGRES_DB: the_room_of_secrets
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: iamgroot
    ports:
      - '5445:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
